### ISSUE TITLE
Remove PostCSS deprecation notice

### ISSUE THREAD

**Issue by thewilkybarkid** [limitlessloop/flex-gap-polyfill#24]
Currently getting:

```
postcss-gap: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration
```

when using. Seems to work fine, but looks like it's worthwhile to upgrade.

**Comment by limitlessloop** [comment]
Thanks for this, I've removed the use of `postcss.plugin` and the depreciation notice should now be gone.
