### ISSUE TITLE
This seems to break my @import at the top of the file. Am I missing anything?

### ISSUE THREAD

**Issue by xdivby0** [limitlessloop/flex-gap-polyfill#38]
I have a css file that looks similar to this:

```
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=Jost:wght@400;600;700&family=Roboto+Slab:wght@400;700&display=swap');

// actual css below here
```

Adding the flex-gap-polyfill postcss plugin breaks this import. I am not 100% sure [this root-rule prepending](https://github.com/limitlessloop/flex-gap-polyfill/blob/e17c9c90ac48c4b45a52a17a6c6397fda3fb7de2/src/index.js#L153) is causing this break but I think so. Am I missing anything?

**Comment by limitlessloop** [comment]
Ah it could be, because it adds a `:root` rule at the top of the file. I might just need to check for any imports and add the rule after those. Thanks for flagging this.

**Comment by xdivby0** [comment]
You are welcome, thank you for doing this project! If I can help or should retest with a different version, hit me up :)

**Comment by limitlessloop** [comment]
Hi @xdivby0 I've just submitted a fix for this. It will now only append the `:root` rule after `@import` rules. This assumes all import rules are at the top of the file. You can try it out by installing the latest version. If you use `postcss-import` it might also be a good idea to put this before `flex-gap-polyfill` in your list of PostCSS plugins.
