### ISSUE TITLE
stuck on transformation stage when using nuxt with vite

### ISSUE THREAD

**Issue by RuDami** [limitlessloop/flex-gap-polyfill#94]
using with:
 "nuxt": "^3.13.2",
 
```
 export default defineNuxtConfig({
    vite: {
      css: {
        postcss: {
          plugins: [require('flex-gap-polyfill')()]
        }
      }
    }
  }
)
```

after "yarn dev" or  "yarn build" postcss warn in console and stuck in random file

> A PostCSS plugin did not pass the from option to postcss.parse. This may cause imported assets to be incorrectly transformed. If you've recently added a PostCSS plugin that raised this warning, please contact the package author to fix the issue.

I'm also try another variant like in [tailwind](https://stackblitz.com/github/nuxt-modules/tailwindcss/tree/docs-examples/examples/postcss-config?file=nuxt.config.ts)  but get the same trouble
```
 export default defineNuxtConfig({
postcss: {
    plugins: {
      'flex-gap-polyfill': {}
    }
  }

)
```

**Comment by gavinmcfarland** [comment]
I'm aware of this issue or one like it. The warning occurs Ibecause of a dependency that uses `postcss.parse`.

https://github.com/gavinmcfarland/flex-gap-polyfill/issues/89

So just to confirm, is it preventing the build from being completed?

**Comment by RuDami** [comment]
Yes. Build just get stuck on `transforming (825) src/RANDOM FILE JS/TS/CSS/SCSS/VUE`

**Comment by RuDami** [comment]
sometimes i see 
```
transforming (816) src/assets/images/Gift/info.svg
 WARN  [vite:css] Lexical error on line 1: Unrecognized text.                                                                                                                           12:23:19 AM

  Erroneous area:
1: unset + var(--fgp-gap-row, 0px)
^..^

```

maybe somethig linked with this?

**Comment by RuDami** [comment]
im create [stackbiz](https://stackblitz.com/edit/github-h7vktb?file=nuxt.config.ts,pages%2Findex.vue) with nuxt and this plugin, but everything works fine inside, and i can't reproduce

**Comment by gavinmcfarland** [comment]
Thank you. I appreciate the feedback and link to demo. I believe another issue is causing the build to get stuck. It may be related to the use of the `unset` keyword in the CSS. It seems like it's attempting to `calc(unset + var(--fgp-gap-row, 0px))`.

Also, could you please let me know which browsers (or browser versions) you are trying to polyfill?

**Comment by RuDami** [comment]
my plan was to run flex-gap-polyfill with vite/legacy to work correctly in safari 12, but unfortunately I can't run it even in a normal build.
I didn't quite understand the question about the browser.
I use the latest stable Chrome, but it doesn't reach it in development mode or in production mode. vite simply doesn't give files to the browser, because it freezes

**Comment by RuDami** [comment]
finally i found the problem. 

i use SFC vue with <style lang="scss" module>.

and some files wont be marked as lang="scss", and your plugin go into an infinite loop trying to disassemble it

**Comment by gavinmcfarland** [comment]
Interesting. Do files marked with scss get transformed with PostCSS or only Sass?

**Comment by RuDami** [comment]
Its doesn't matter, you can pick lang="sass" if you want. My mistake is that i forgot about add lang type to some files. If you want to debug this infinite loop i can sent you stackblitz reproduction 
Maybe you can set some trows with warning

**Comment by RuDami** [comment]
And yes, i think lang=scss transpile sass to, cos both of it uses "saas" lib

**Comment by gavinmcfarland** [comment]
Thanks. What I was trying to figure out was why it's getting hung up on files that don't have the lang="scss" or lang="sass" attribute. If you can create a stackblitz repo, that would be great and I can investigate further. ❤️

**Comment by RuDami** [comment]
im update previous [link](https://stackblitz.com/edit/github-h7vktb?file=components%2FSkeleton.vue)
Please see asap, cos idk how long stackblitz save this

**Comment by RuDami** [comment]
if you want to do it correctly change <style module> to  <style lang="scss" module> in Skeleton

<img width="828" alt="Снимок экрана 2024-10-20 в 02 49 45" src="https://github.com/user-attachments/assets/3a6d14f1-be38-4bfe-a10d-9d3eecda5c21">

**Comment by gavinmcfarland** [comment]
Thank you! I've created a fork.
